# Generated by Django 3.1.7 on 2021-05-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
